stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "kareemhijjawi5/my-python-app:latest"  # Use your Docker Hub repository

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE .
    - docker login -u "username" -p "password"  # Log in to Docker Hub
    - docker push $DOCKER_IMAGE  # Push the image to Docker Hub
    - docker images  # List images to confirm the build and push
  only:
    - main

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Deploying to localhost..."
    - docker login -u "username" -p "password"  # Log in to Docker Hub
    - docker pull $DOCKER_IMAGE  # Pull the image from Docker Hub
    - docker images  # Verify if the image is present
    - docker run -d -p 8000:8000 $DOCKER_IMAGE  # Run the container
    - docker ps
  only:
    - main
#wwhamzeh
