stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "kareemhijjawi5/my-python-app:latest"  

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE .
    - docker login -u "username" -p "password"  
    - docker push $DOCKER_IMAGE  
    - docker images  
  only:
    - main

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Deploying to localhost..."
    - docker login -u "username" -p "password"  
    - docker pull $DOCKER_IMAGE  
    - docker images 
    - docker run -d -p 8000:8000 $DOCKER_IMAGE  
    - docker ps
  only:
    - main

